export const ICONS = {
  cutlery: require('../assets/icons/cutlery.png'),
  search: require('../assets/icons/search.png'),
  like: require('../assets/icons/like.png'),
  user: require('../assets/icons/user.png'),
  nearby: require('../assets/icons/nearby.png'),
  basket: require('../assets/icons/basket.png'),
  burger: require('../assets/icons/burger.png'),
  rice: require('../assets/icons/rice.png'),
  pizza: require('../assets/icons/pizza.png'),
  snacks: require('../assets/icons/snacks.png'),
  sushi: require('../assets/icons/sushi.png'),
  noodles: require('../assets/icons/noodles.png'),
  hotdog: require('../assets/icons/hot-dog.png'),
  salad: require('../assets/icons/salad.png'),
  star: require('../assets/icons/star.png'),
  back: require('../assets/icons/back.png'),
  list: require('../assets/icons/list.png'),
  calories: require('../assets/icons/calories.png'),
  pin: require('../assets/icons/pin.png'),
  mastercard: require('../assets/icons/mastercard.png'),
  car: require('../assets/icons/car.png'),
  avatarMale: require('../assets/icons/avatar-male.png'),
  avatarFemale: require('../assets/icons/avatar-female.png'),
};
